on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

name: update-tf-module-example-latest-version

jobs:
  update-tf-example-versions:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
    steps:
      - name: Checkout Latest Tag
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Update Terraform Module Source
        run: |
          NEW_TAG=${{ github.ref_name }}
          for file in $(find . -name "*.tf" -type f); do
            if grep -q 'ref=' "$file"; then
              sed -i 's|\(ref=\)[^"]*|\1'"${NEW_TAG}"'|' "$file"
              echo "Updated $file"
            else
            echo "Skipped $file (no ref= found)"
            fi
          done

      - name: Commit and Push Changes
        run: |
          git config --global user.email "devops@nowpensions.com"
          git config --global user.name "NOW DevOps"
          git add main.tf CHANGELOG.md
          git commit -m "Update Terraform module example source to ${NEW_TAG}"
          git push