on:
  push:
    tags:
      - '[0-9][0-9].[0-9][0-9][0-9].[0-9]'

name: update-tf-example-versions

jobs:
  update-tf-example-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Update Terraform Source in All .tf Files
        run: |
          NEW_TAG=${{ steps.new_tag.outputs.new_tag }}
          # Find all .tf files and update only if they contain ref=
          for file in $(find . -name "*.tf" -type f); do
            if grep -q 'ref=' "$file"; then
              sed -i 's|\(ref=\)[^"]*|\1'"${NEW_TAG}"'|' "$file"
              echo "Updated $file"
            else
            echo "Skipped $file (no ref= found)"
            fi
          done