on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

name: update-tf-module-example-latest-version

jobs:
  update-tf-example-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Update Terraform Module Source
        run: |
          NEW_TAG=${{ steps.new_tag.outputs.new_tag }}
          for file in $(find . -name "*.tf" -type f); do
            if grep -q 'ref=' "$file"; then
              sed -i 's|\(ref=\)[^"]*|\1'"${NEW_TAG}"'|' "$file"
              echo "Updated $file"
            else
            echo "Skipped $file (no ref= found)"
            fi
          done